[package]
name = "chain-monitor"
version = "0.1.0"
authors = ["Xudong Yang <fanderous@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.8.0"
hex = "0.3.2"
serde = "1.0.98"
serde_json = "1.0.40"
